name = "gilded_rose"
version = "1.0.0"
description = "🌹 The Gilded Rose refactoring kata in Gleam"
licences = ["Apache-2.0"]

[repository]
type = "github"
user = "giacomocavalieri"
repo = "gilded_rose"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.4 and < 2.0.0"
